apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-moaldujo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-moaldujo:1be987a94bcdedec9c513751c1bbcc08749c47b9@sha256:82c82ca9985de79754d750681f058a48d86b4bbbf927032400c93a5d381dd2e6
          name: container-image
